service: countries-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  app:
    handler: build/lambda.default
    timeout: 30 
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

custom:
  cors:
    origin: '*'
    headers:
      - Content-Type
      - Authorization
    allowCredentials: false
